export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        terracotta: {
          DEFAULT: '#c96442',
          light: '#d97757',
          dark: '#b53333',
        },
        parchment: '#f5f4ed',
        ivory: '#faf9f5',
        sand: '#e8e6dc',
        charcoal: '#4d4c48',
        olive: '#5e5d59',
        stone: '#87867f',
        midnight: '#141413',
        darkSurface: '#30302e',
        warmSilver: '#b0aea5',
        coral: '#d97757',
        borderCream: '#f0eee6',
        borderWarm: '#e8e6dc',
        ringWarm: '#d1cfc5',
        ringSubtle: '#dedc01',
        ringDeep: '#c2c0b6',
      },
      fontFamily: {
        serif: ['Georgia', 'Cambria', 'Times New Roman', 'serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['JetBrains Mono', 'Consolas', 'monospace'],
      },
      fontSize: {
        display: ['4rem', { lineHeight: '1.10', fontWeight: '500' }],
        'section-heading': ['3.25rem', { lineHeight: '1.20', fontWeight: '500' }],
        'subheading-lg': ['2.3rem', { lineHeight: '1.30', fontWeight: '500' }],
        'subheading': ['2rem', { lineHeight: '1.10', fontWeight: '500' }],
        'subheading-sm': ['1.6rem', { lineHeight: '1.20', fontWeight: '500' }],
        'feature-title': ['1.3rem', { lineHeight: '1.20', fontWeight: '500' }],
        body: ['1.0625rem', { lineHeight: '1.60' }],
        'body-lg': ['1.25rem', { lineHeight: '1.60' }],
        'body-sm': ['0.9375rem', { lineHeight: '1.60' }],
        caption: ['0.875rem', { lineHeight: '1.43' }],
        label: ['0.75rem', { lineHeight: '1.60', letterSpacing: '0.012em' }],
      },
      borderRadius: {
        sharp: '4px',
        'subtle-round': '6px',
        'comfortable': '8px',
        'generous': '12px',
        'feature': '16px',
        'highly': '24px',
        'max': '32px',
      },
      boxShadow: {
        ring: '0px 0px 0px 1px',
        'ring-warm': '0px 0px 0px 1px #d1cfc5',
        'ring-terracotta': '0px 0px 0px 1px #c96442',
        whisper: '0px 4px 24px rgba(0,0,0,0.05)',
        'whisper-lg': '0px 8px 32px rgba(0,0,0,0.08)',
      },
      spacing: {
        '3': '3px',
        '4': '4px',
        '6': '6px',
        '10': '10px',
        '12': '12px',
        '20': '20px',
        '30': '30px',
      },
    },
  },
  plugins: [],
};